import GPTModel from "./GPTModel.mjs";

class GPTIdeasGenerator extends GPTModel {
  constructor() {
    super();
    this.model = "gpt-4";
    this.systemMessage =
      "You are a highly creative and informed content strategist specializing in the electronics retail sector. Your primary goal is to generate short video ideas that are compelling, informative, and perfectly tailored to the interests of electronics enthusiasts and professionals. The content ideas generated must be according to the instructions passed to you as a prompt. Ensuring each idea is visually engaging and suitable for AI-driven, no-face video formats. ";
  }

  async generateIdeas() {
    try {
      const result = await this.OpenAiGPT.chat.completions.create({
        messages: [
          {
            role: "system",
            content: this.systemMessage,
          },
          {
            role: "user",
            content: `Develop a series of compelling and innovative video ideas centered around soldering, how to solder and tips and tricks when soldering. These ideas should be suitable for short-format videos designed for an AI-driven production process, where all aspects, from scripting to visuals, are generated by AI without human supervision. The video format should be no-face to emphasize the content and visuals.Consider the following guidelines: Target Audience Relevance: Tailor the video content to appeal directly to Ebits' target demographic, focusing on topics that resonate with enthusiasts and professionals in electronics and software development. Engaging and Informative Content: Ensure each video idea offers value, either by educating, teaching, informing, or entertaining the audience. The content should be easily digestible and suitable for a short video format, ideal for an Instagram campaign. AI-Generated Visuals: As the visuals will be created entirely by AI, suggest ideas that lend themselves to visually appealing and relevant imagery. This could include animated diagrams, infographics, or abstract representations of electronic concepts. Branding and Marketing Goals: Align the video ideas with Ebits' branding and marketing objectives. The content should be designed to enhance brand awareness, drive traffic to the webshop, and encourage community engagement.Maximizing Engagement Metrics: Focus on concepts that are likely to drive high engagement metrics such as views, likes, shares, and comments. Consider what's currently trending or has been historically popular in the electronics and software development communities.Provide a list of video ideas, each with a brief description that encapsulates the theme, potential visuals, and the intended impact on the viewer. Remember, the overarching goal is to increase brand interest and encourage visits to Ebits' webshop and online community,`,
          },
        ],
        model: this.model,
      });
      console.log(result.choices[0].message.content);
      return result.choices[0].message.content;
    } catch (e) {
      throw new Error(
        "Ideas Generator module failed to generate ideas: ",
        e.message
      );
    }
  }

  async generateIdeasForTopic(topic) {
    try {
      const result = await this.OpenAiGPT.chat.completions.create({
        messages: [
          {
            role: "system",
            content: this.systemMessage,
          },
          {
            role: "user",
            content: `Develop a series of compelling and innovative video ideas centered around ${topic}. These ideas should be suitable for short-format videos designed for an AI-driven production process, where all aspects, from scripting to visuals, are generated by AI without human supervision. The video format should be no-face to emphasize the content and visuals.Consider the following guidelines: Target Audience Relevance: Tailor the video content to appeal directly to people interested in electronics, development and overall the tech industry, focusing on topics that resonate with enthusiasts and professionals in electronics and software development. Engaging and Informative Content: Ensure each video idea offers value, either by educating, teaching, informing, or entertaining the audience. The content should be easily digestible and suitable for a short video format, ideal for an Instagram, YouTube and TikTok campaign. AI-Generated Visuals: As the visuals will be created entirely by AI, suggest ideas that lend themselves to visually appealing and relevant imagery. This could include animated diagrams, infographics, or abstract representations of electronic concepts. Branding and Marketing Goals: Align the video ideas with a compamy resonating around product development, electronics design and production's branding and marketing objectives. The content should be designed to enhance brand awareness, drive traffic to a webshop, and encourage community engagement. Maximizing Engagement Metrics: Focus on concepts that are likely to drive high engagement metrics such as views, likes, shares, and comments. Consider what's currently trending or has been historically popular in the electronics and software development communities.Provide a list of video ideas, each with a brief description that encapsulates the theme, potential visuals, and the intended impact on the viewer. Remember, the overarching goal is to increase brand interest and encourage visits to Ebits' webshop and online community,`,
          },
        ],
        model: this.model,
      });
      console.log(result.choices[0].message.content);
      return result.choices[0].message.content;
    } catch (e) {
      throw new Error(
        "Ideas Generator module failed to generate ideas: ",
        e.message
      );
    }
  }

  setGenerativeModel(model) {
    if (model.length > 4) {
      this.model = model;
    } else if (model.length < 4) {
      throw new Error(
        `Error in Ideas Generator module, not a valid GPT model: ${model} Provide a valid GPT model`
      );
    }
  }
}

export default GPTIdeasGenerator;
